// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vayzyztyqmdoqooxvouq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZheXp5enR5cW1kb3Fvb3h2b3VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTAyNTMsImV4cCI6MjA2MzgyNjI1M30.vVIaEgSJ-kMDhHlaml5BYAL2w_9-ca0TF-ZhKgqdYSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);